### ISSUE TITLE
Terminal cient?

### ISSUE THREAD

**Issue by irevenko** [darylhjd/mangadesk#1]
why desktop when it is TUI

**Comment by darylhjd** [comment]
oh yea you are right... thanks for pointing it out!

**Comment by darylhjd** [comment]
Fixed with https://github.com/darylhjd/mangadesk/commit/21e985fa14138736cb1816155026119d72e7d44b

**Comment by irevenko** [comment]
good job on this one, wanna connect? discord: **Ilya Revenko#4742**

**Comment by darylhjd** [comment]
thanks! i don't use discord that much most of the time but sure :)
