### ISSUE TITLE
[Feature Request] Quit & Selection

### ISSUE THREAD

**Issue by Luc-Saccoccio** [darylhjd/mangadesk#12]
Probably add a keybinding to quit the application, or mention it if there's one ^^

`q` would probably be a good choice (intuitive, used in a lot of TUI apps)

Also, why not adding alternatives keybinds (Space for example) to select items, or a "Visual Mode" to select a bunch of them without having to select each one manually ?

**Comment by darylhjd** [comment]
Ah I never thought about a quit button since i've been using Ctrl+C all this while.

I also didnt want to use pure letter key bindings because the user might be doing quite a bit of typing.

I'm not too sure what you mean by alternative keybinds or visual mode. do you mean just different key bindings; do u mean opening a GUI to select multiple chapters?

**Comment by Luc-Saccoccio** [comment]
> I also didnt want to use pure letter key bindings because the user might be doing quite a bit of typing.

I know, but in some contexts (Recently Updated Mangas, Chapter Selection it could be useful. That or adding a button "Quit" in the login screen would be pretty good. 

> I'm not too sure what you mean by alternative keybinds or visual mode. do you mean just different key bindings; do u mean opening a GUI to select multiple chapters?

If you see what is Visual mode in Vim, it's the same thing (more or less) : Press `v` (or whatever keybind you want), move from startpoint to endpoint => All the characters between the two points are selected. It would be kinda the same : Enter visual mode, select a range of chapters to download, confirm by pressing Enter (for example).

**Comment by darylhjd** [comment]
i actually like the `v` key idea, altho implementing that might be a little painful🤔

**Comment by darylhjd** [comment]
I have added Ctrl + A support into the application. Not really like what you described, but I believe it will suffice. As such, I will be closing this issue!

**Comment by Luc-Saccoccio** [comment]
Not quite what I add in mind, but still a great improvement. Thanks :D
