### ISSUE TITLE
[Feature Request] Retrive read status of chapters

### ISSUE THREAD

**Issue by SMylk** [darylhjd/mangadesk#16]
Hi,

Would it be possible to show the read status of the different chapters as far as i remember mangadex website had a row for this.

**Comment by scott-tancock** [comment]
- Looks like the API exposes /manga/{id}/read which returns a list of UUIDs of all read chapters.  
- When looking at a particular manga (chapter list loaded), everything in that list can be marked 'read' and everything not in that list can be marked 'unread'.  
- On the main follows page, we'd have to work out the volume/chapter of the most recently read chapter.  The last item in the list of read markers is the most recently read chapter.  If we submit this to /chapter/{id}, an object with the volume and chapter number is returned.  This would have to be performed for all follows on the page of 100.

**Comment by darylhjd** [comment]
for the last point i would probably just go with a "has new updates" column perhaps. no need to get last volume/chapter.

**Comment by SMylk** [comment]
Tested the new build, works wonderfully.
