### ISSUE TITLE
Download everything?

### ISSUE THREAD

**Issue by pmwoodward3** [darylhjd/mangadesk#18]
Would there be an easy way to queue up everything on mangadex and keep track of new releases?

**Comment by darylhjd** [comment]
sorry im not quite sure what you are asking

**Comment by pmwoodward3** [comment]
Sorry, let me reword that. If instead of just picking/selecting/searching for specific manga, is there anyway I can queue up all the manga to be downloaded? Essentially asking if there's any way I could use this tool to download and keep updated all of the manga on mangadex.

**Comment by darylhjd** [comment]
you mean u wanna download _all_ the manga on mangadex?

**Comment by pmwoodward3** [comment]
Correct. Sorry if that's way outside of the scope of this.

**Comment by darylhjd** [comment]
haha no worries.

even discounting the issue of having enough storage space to achieve that; i believe the api doesnt provide that kind of functionality and this tool sure wasnt written with the original intention of doing that.

as such, im sorry to be the bearer of disappointing news but: no, this program would utterly fail for that task.


PS: maybe ill submit a PR introducing this :P
