### ISSUE TITLE
[Custom Command] Added my own selection command

### ISSUE THREAD

**Issue by nayomi3i** [darylhjd/mangadesk#19]
I don't really know if I implemented it correctly since I had to try to teach myself Go from nothing just to make it in only like, a day. But I found the whole, Cmd+E, next, Cmd+E, tedious and wanted to implement a Select All. I found a work around, I think maybe someone would find it useful or you could implement yourself in a more robust way. Anyways, this is it,

I don't know how to use git so I'm probably showing this wrong 😅
And also since I'm not experienced in Go I didn't want to do git pull or anything like that (don't know how and might do it wrong), the command is just for personal use and it might be cool if it was proper.

<img width="617" alt="MangaHandler" src="https://user-images.githubusercontent.com/77587392/119278662-7cbe2480-bbdb-11eb-874e-764800e9c827.png">
<img width="618" alt="CustomFunction" src="https://user-images.githubusercontent.com/77587392/119278663-7fb91500-bbdb-11eb-99f3-cc06407f9012.png">

https://user-images.githubusercontent.com/77587392/119278732-fd7d2080-bbdb-11eb-89b9-1a907ade3913.mp4

**Comment by nayomi3i** [comment]
It would be nice to add some kind of language filter to the mangalist. I don't know how to work with the API so I don't know if I could implement it myself. But possibly add something like, a new page that you can do like ctrl+[someKey] that will find all of the available languages, allow you to select a language, and then filter shown chapters like that?

I really don't know, but thatd be convenient.

**Comment by darylhjd** [comment]
I have added these 2 features in the latest commit.

**Comment by darylhjd** [comment]
Welcome to the Golang community :)

Working with Git may be scary but it is easy once you get a hang of it. Here are the steps:
1. Fork the current repository that you want to contribute to.
    - This will add a copy of the repository into your own account.
2. Add your features/bug fixes into your forked repository.
    - Remember to push your changes into the repository!
3. Once you are happy with the changes, head on over to the current repository's `Pull Requests` tab. 
    - Then, create a new pull request.
    - Click `Compare across forks`.
4. Choose the base repository to _pull into_ (the repo you want to contribute to), and the head repository to _push from_ (this is where you select your forked repo).
    - Remember to read the contributing guidelines for whichever repo you want to contribute to.
