### ISSUE TITLE
No indication of downloading

### ISSUE THREAD

**Issue by Yoshua-chan** [darylhjd/mangadesk#2]
When downloading manga, there isn't any indication whether it's being downloaded and there is no progress indication

**Comment by darylhjd** [comment]
I'll see the feasibility of doing this for a TUI. I did want it added in originally, but this might take longer to implement.

**Comment by darylhjd** [comment]
https://github.com/darylhjd/mangadesk/commit/8c5cc30b7642ee2c35c2bf4c68955a155be5b920

User will now be notified when downloads are finished.
