### ISSUE TITLE
[BUG] Chapters missing for solo leveling

### ISSUE THREAD

**Issue by lorddickfist** [darylhjd/mangadesk#20]
Chapters are skipped from 5 to 65 for solo leveling checked mangadex.tv and all the chapters are there. Wondering if its because I am not a member? 
![Screenshot from 2021-05-24 10-13-09](https://user-images.githubusercontent.com/22435766/119383910-cc9ef900-bc78-11eb-8654-1fef2c7f7585.png)

Reproduce: open solo leveling and check the chapter list
expected: chapters 6-64 should be present
actual: chapter 6-64 are missing

**Comment by darylhjd** [comment]
this was reported before, and the reason was that the servers dont currently serve those chapters (they were apparently removed by the scanlators)
