### ISSUE TITLE
Chapter folder is empty?

### ISSUE THREAD

**Issue by MrComexs** [darylhjd/mangadesk#23]
Don't know why but for some reason I'm unable to download the pages of the any manga. the program makes the folder of the series and the chapter but the chapter folder is empty? Can anyone tell me what I did wrong.

**Comment by darylhjd** [comment]
please provide more information such as which manga/chapter so i can better diagnose.

**Comment by MrComexs** [comment]
It doesn't work for most of the manga's that I have tried but I was finally able to download a chapter. Mangas that I have tried to download but didn't work are "I Shaved. Then I Brought a High School Girl Home" , "My New Wife Is Forcing Herself to Smile" "Shikimori's Not Just a Cutie" and many more just the latest chapters. The only manga I was able to download was "The World of Otome Games Is Tough for Mobs".

**Comment by darylhjd** [comment]
hmm i am able to download these without any problem.

does the program tell you that the download queue is finished?

as extra information, may i know which language you are downloading, and perhaps whether you have changed the default download directory.

**Comment by MrComexs** [comment]
I just tried it again on "I Shaved" and the download queue said that it was all good and there aren't any errors. I didn't change any of the setting. All I just did was run the exe and download a random chapter to see if it works. It is also left on English.

**Comment by darylhjd** [comment]
are you by any chance using any network that may have some form of firewalls?

**Comment by MrComexs** [comment]
it wouldn't make sense since I was able to download "the world of otome games is thought for mobs".

**Comment by darylhjd** [comment]
i have uploaded a test build in the latest release. it is labelled with a test build suffix.

you may try changing the new `forcePort443` setting to see if that helps. also, I have made the errors more verbose. if you encounter errors, do let me know.

**Comment by MrComexs** [comment]
The new update worked! Thank you I'm very happy.

**Comment by darylhjd** [comment]
ok thats good, but did you change something to make it work?
