### ISSUE TITLE
Cannot download chapters from mangas that has ":" in their name

### ISSUE THREAD

**Issue by highmirai** [darylhjd/mangadesk#26]
I tried to download "JoJo's Bizarre Adventure Part 6: Stone Ocean (Colored)", and I think that since it has a colon in it's name, it cannot create the folder so it cannot download the pages.

![Screenshot_64](https://user-images.githubusercontent.com/61987827/120383878-b56da480-c325-11eb-8193-374b03d73e68.png)
I think a patch for this would be to check if the manga name or chapter name contains a colon and if it does, it changes it to a dash.

Thanks.

**Comment by darylhjd** [comment]
hmm thats weird the current programme removes invalid characters alr.

thanks for reporting, ill check it out

**Comment by darylhjd** [comment]
oh.... i see whr it went wrong haha ill make a fix in due time!
