### ISSUE TITLE
[Bug?] mangadesk_x64 only shows 'reading' manga.

### ISSUE THREAD

**Issue by KantelJFA** [darylhjd/mangadesk#27]
Today I discovered this application, and, on login, I noticed it didn't actually show any manga that I didn't had in the 'reading' category. The thing is, most of my followed manga where in the 'to_read' category, so I was wondering if it is a bug, the intended behavior, or something else happened.

I expected to get more than 100 mangas in that list, instead I got merely 19.

![Captura de pantalla de 2021-06-04 19-16-18](https://user-images.githubusercontent.com/61141058/120839681-88a9cf00-c569-11eb-8e48-8895b9031968.png)

**Comment by darylhjd** [comment]
I believe marking a manga as "to_read" is not the same as following it.
