### ISSUE TITLE
[Bug] Mangadesk remembers password even after being uninstalled and reinstalled

### ISSUE THREAD

**Issue by zchlrnr** [darylhjd/mangadesk#28]
Documentation is unclear as to how I get the password un-stored.

It seems to try and remember my authentication data even after I've uprooted and uninstalled the whole git repo.

Where is it storing it and how can I delete it?

Using v0.5.1 on Manjaro Linux
Kitty Terminal Emulator

**Comment by darylhjd** [comment]
hi, its stored in the `cred` file in the `usr` folder, same place as where the usr_config file is stored. 

will have to update documentation for this.

**Comment by darylhjd** [comment]
note that usually you will not need to delete the credentials file by itself, as the application will delete this file when you logout.
