### ISSUE TITLE
Implementing "paste" shortcut

### ISSUE THREAD

**Issue by BaccanoMob** [darylhjd/mangadesk#29]
It be cool if you can have ctrl+v shortcut to paste to avoid typos in the while searching. Also pasting a complete title might help narrow down lengthy searches.

**Comment by darylhjd** [comment]
copy paste should be enabled by default. 

which terminal are you using?

**Comment by BaccanoMob** [comment]
I am not sure how to answer that properly. Im using windows 10 and ran the mangadesk_win64.exe (tried with 32.exe as well) file.

Ctrl + C -> Closes the terminal (though I doubt I might use copy)
Ctrl + V -> does nothing

**Comment by darylhjd** [comment]
ah ok.

for windows, what you need to do is:

1. right click on the title bar
2. Click `Properties`.
3. In the `Options` tab, enable the `Use Ctrl+Shift+C/V` option.
4. You can now use Ctrl+Shift+C/V to copy and paste.
