### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hyper3557** [darylhjd/mangadesk#31]
Does not work on Mac. You have specified a Mac file in the release page. After downloading, a document is downloaded. Thats it? Is there more procedure to install it properly. pls specify more

**Comment by darylhjd** [comment]
hey there. the application doesnt need to be installed as it runs as a standalone executable. 

when you download the program, its a binary executable and not a document.

you can find the instructions for running it in the Usage section of the README. 

if you still cant seem to make it run, just let me know.

**Comment by Hyper3557** [comment]
Some people from the Mangadex discord helped me out in installing it and it works fine now, therefore I closed the issue. Still I appreciate that you contacted me.
