### ISSUE TITLE
Search does't seem to find all works 

### ISSUE THREAD

**Issue by Madoka03** [darylhjd/mangadesk#32]
First mangadesk works stable without problems, thanks for that great work.

I do not know if my problem is a bug or simple a missing flag when Mangadesk send a request to the api but i can't find any manga that has the most explicit content rating on Mangadex. Allows the api to search for such titles?

**Comment by darylhjd** [comment]
yes the default is that explicit content is not included in search results.

ill see what i can do to make this a toggled option.

**Comment by darylhjd** [comment]
Will be releasing a new build for this. Just keep a look out.

**Comment by Madoka03** [comment]
That was very fast, thanks.
