### ISSUE TITLE
[Feature Request] Download as CBZ

### ISSUE THREAD

**Issue by wisewtf** [darylhjd/mangadesk#33]
Would love to have an option to download directly as a cbz or zip. This is because my self-hosted manga library only works with cbz or zip files and image format folders are not contemplated, plus I would argue that for manga and comics in particular cbz (or the lesser used and lesser compatible cbr) are almost a standard.

In my opinion would just shoot up the usability of this application tenfold.
Thank you for your consideration.

**Comment by darylhjd** [comment]
aight ill see what i can do

**Comment by darylhjd** [comment]
im learning how to use a makefile lol. then ill release the binaries for this.
