### ISSUE TITLE
[Question] Authentication error

### ISSUE THREAD

**Issue by Drag0nDev** [darylhjd/mangadesk#37]
While I tried to log in again on my account via the terminal app I currently get this error.
![image](https://user-images.githubusercontent.com/34603014/127555313-00714bb6-4b6e-46b9-bc2a-203569337231.png)

Is this due to a failure at my end or due to a change on their apis end?

**Comment by darylhjd** [comment]
are you able to log in normally on the normal website?

**Comment by darylhjd** [comment]
its ok i figured out the problem.
