### ISSUE TITLE
[Feature Request] Adding Mangadesk to AUR

### ISSUE THREAD

**Issue by SmellsNice** [darylhjd/mangadesk#38]
Pretty much it, it would be convenient if an aur package was available.

**Comment by darylhjd** [comment]
i have no idea how to navigate AUR unfortunately, so I would require someone else that knows how to set it up there.

**Comment by AmaanHUB** [comment]
@SmellsNice, present for you [mangadesk AUR](https://aur.archlinux.org/packages/mangadesk)

I just need to create a pull request to put it in the README.md
