### ISSUE TITLE
[Feature Request] Ability to set a downloads folder outside the mangadesk directory

### ISSUE THREAD

**Issue by SmellsNice** [darylhjd/mangadesk#39]
**Is your feature request related to a problem? Please describe.**
Currently if you change the DownloadDir the directory you set will always be inside the mangadesk folder. This makes it harder to organize big collections in one folder.

**Describe the solution you'd like**
It would be nice if DownloadDir used ~/Pictures/Mangas for example instead of creating a ~/Pictures/Mangas folder in its own folder.

**Comment by darylhjd** [comment]
you can actually make the downloads go to any folder by starting your path with `/` or using environment variables like `$HOME`, but you cant do it with `~` since those are usually expanded by the terminal and cant be done programmatically.

**Comment by SmellsNice** [comment]
> you can actually make the downloads go to any folder by starting your path with `/` or using environment variables like `$HOME`, but you cant do it with `~` since those are usually expanded by the terminal and cant be done programmatically.
> 
> for example to save the files in the Downloads folder u can set the path up to be `/home/usr/Downloads` or `$HOME/Downloads`

Thank you that actually worked, solved.
