### ISSUE TITLE
[ Question ] Were the files are supposed to be downloaded?

### ISSUE THREAD

**Issue by lag00n** [darylhjd/mangadesk#4]
Just for example, I've tried to download some chapters from the manga "Eight" (the same as the shown on example gif), and I just can't find them anywhere. I've tried to run `find / -iname Eight` and there's no results found.

Where can I find the downloaded files?

**Comment by Karem34** [comment]
looking at the source code, it should be in the Downloads folder

### in Unix
`~/Downloads/[english title]/chapter/`

https://github.com/darylhjd/mangadesk/blob/5393ae5d2eb64150dcec5840ba1c5dbc4621a8cc/helpers.go#L72

**Comment by jakeisnt** [comment]
In the code it's hardcoded with a lowercase `d`, so I don't think that's the case (as shown below) looks like it tries to target a `downloads` folder relative to the directory in which you run `mangadesk`, and creates the folder if it doesn't exist.
https://github.com/darylhjd/mangadesk/blob/5393ae5d2eb64150dcec5840ba1c5dbc4621a8cc/helpers.go#L21

**Comment by darylhjd** [comment]
Thanks for the replies everyone. 

Indeed, the downloads are found in the `downloads` folder that is created in the same directory you run the application from. You do not need to create the folder manually as the program will create it automatically if it does not exist.

I have updated the README to make it clearer where the downloads are stored. https://github.com/darylhjd/mangadesk/commit/6e7ccdf15f2a3d9bc18c11cdd3d09847238c6fda
