### ISSUE TITLE
Chapter not showing up

### ISSUE THREAD

**Issue by rischhart** [darylhjd/mangadesk#40]
So... I wanted to download the full Manga of Solo Leveling. But there is a big gap between chapters 5 and 65. Also, the last two Chapters are missing. I didn't check if any of the other chapters are... On Manganato the manga has all chapters from 0 up to 162. Do you have any suggestions why this might happen?

**Comment by darylhjd** [comment]
i believe one of the scanlation groups decided to remove all their uploaded chapters due to some disagreement with mangadex, so now theres a big gap of chapters.
