### ISSUE TITLE
Win 10 Trojan

### ISSUE THREAD

**Issue by LTech77** [darylhjd/mangadesk#41]
Hello,
today, Win 10 integrated Antivirus reported to me that "Mangadesk_win64.exe" is a Trojan.
I have used this app before without any Problem since today. 
The Massage is in German, but I think it is clear.
![image](https://user-images.githubusercontent.com/83650927/130515878-83ee0fa0-4321-4193-b3d4-af66300089b8.png)

**Comment by darylhjd** [comment]
should be a false positive and safe to ignore.

but ill keep this open for now.
