### ISSUE TITLE
[BUG] Guest login - for explicit content, chapter listing not working

### ISSUE THREAD

**Issue by dimox99** [darylhjd/mangadesk#47]
**Describe the bug**
As title states - in guest login it's possible to search for explicit content and respective manga titles will show up in the search result box if you enable the checkbox. So far working as intended. But once you open such a manga to browse through the chapter list you get "no results" even if there should be entries listed.

I tried to open a manga with such content directly in a private browser window to prevent unwanted interaction. It's possible, the website still lets you access explicit (or rather "filtered out") content if you know the manga ID. It will, however, warn you about that and asks for permission to proceed - looks like this:

![grafik](https://user-images.githubusercontent.com/90607824/133409996-852236b7-8617-4490-8e8d-b5ac76b25b8e.png)

Once you confirm you can see the chapters and read/access them like normal. I'm not sure whether this is new behaviour after the recent API change. Normally I'm logged in on the website and won't be bothered by such requesters.

**Comment by darylhjd** [comment]
lol do u have an example manga i can use😂

**Comment by dimox99** [comment]
So you want me to provide links to pr0n? As you wish... :rofl:

Okay, jokes aside. I guess any hentai should do, let me just look up a random one that actually has chapters and is readable through the website:

ID:
545779a2-6348-40bf-b251-10305e939a5f

This one has three English chapters. You can search for the title in Mangadesk, it will correctly show up if you allow searching for explicit content, so far so good. Chapters won't show, list is empty.

**Comment by darylhjd** [comment]
download latest release for fix (hopefully). thanks for valuable info!
