### ISSUE TITLE
[Feature Request] display the "group" on manga page

### ISSUE THREAD

**Issue by dimox99** [darylhjd/mangadesk#48]
The manga page currently has columns for chapter number, language, title, download status and read status

This is sufficient if there's only one group working on a manga, but it's likely to see different groups working on the same series. And not necessarily in succession, so sometimes the same chapter gets uploaded by two or even more groups and if they don't differ in title or don't even have titles at all you cannot tell them apart - currently looks like this:

![grafik](https://user-images.githubusercontent.com/90607824/133441624-37b977ac-7b0c-4029-9e7b-34be567ffd28.png)

Right now, I have to download both chapters to identify which one I want/need.
On the other hand, columns for download status and read status can be narrowed if you have to.

Not sure if it's necessary to also add the group to the target folder name for downloading. I leave that up to your decision.

**Comment by darylhjd** [comment]
ok this one is non-trivial so expect not to see much updates on this so far (im also busy with uni atm)

**Comment by dimox99** [comment]
Feared so - guess this would have been implemented already, if it was a three lines of code no-brainer.
But I'm glad you consider my suggestion instead of flat-out rejecting it.

Good look on your studies.

**Comment by darylhjd** [comment]
it's doable so i wont close it. i just need the time to implement it haha. 

i could just slap some code to get it to work for now tho, and then find a better solution later on.

**Comment by dimox99** [comment]
Good to know. I'll leave that to your discretion and see what happens.

**Comment by darylhjd** [comment]
well... u know the drill, download latest release blah blah

enjoy!
