### ISSUE TITLE
[Feature] Configure manga download folder

### ISSUE THREAD

**Issue by jakeisnt** [darylhjd/mangadesk#5]
Rather than hardcoding paths, relative or absolute, the program should allow the user to configure where they'd like the manga to be stored. This could read from an environment variable, a command line argument, a config file or all three - but this program would be more robust if it didn't use the hardcoded `downloads` relative path!

https://github.com/darylhjd/mangadesk/blob/5393ae5d2eb64150dcec5840ba1c5dbc4621a8cc/helpers.go#L21

If you aren't interested in making this configurable, I'd appreciate it if the folder could be something discrete, like $HOME/.mangadesk/{files}, so that the files aren't easily visible when not using mangadesk.

**Comment by darylhjd** [comment]
Thanks for the feedback!

I indeed am thinking of making certain settings configurable, such as the download folder, language selection etc... 

Depends on if I have the time to figure it out :)

**Comment by darylhjd** [comment]
@jakeisnt the current master branch supports setting custom directories. however, you cannot use any environment variables (e.g. $HOME) or non-absolute paths (e.g. tilde `~` on Linux). 

you can change it by going to `globals/settings.go` and setting the `DownloadDir` variable. 

might not be the best but it could work for now. perhaps you wanna give it a try?

**Comment by perfectayush** [comment]
I am using a shell script hack for this, I have a shell script in load path called `manga`.

```shell
#!/usr/bin/env bash

cd ~/manga_downloads/
exec mangadesk $@
```

And in `~/manga_downloads` directory, I have setup a` downloads` symlink pointing back to the same directory
```shell
cd ~/manga_downloads
ln -s . downloads
```
This downloads the Manga in `~/manga_downloads` dir. In the meantime before this feature is implemented, you can use this. @darylhjd Thanks for your work, came to know about this from r/commandline.
