### ISSUE TITLE
[Feature Request] Generate & Embed ComicInfo.xml when creating cbz/zip files

### ISSUE THREAD

**Issue by Critical-Impact** [darylhjd/mangadesk#51]
**Is your feature request related to a problem? Please describe.**
I read manga through Komga, at present none of the information about the manga is saved into the zip/cbz file created.

**Describe the solution you'd like**
Would it be possible to create and embed a ComicInfo.xml (if a zip is selected to be made). Obviously this would need to be created by parsing the information coming back from mangadex's API but this seems like it should be possible.

**Additional context**
I've already downloaded quite a few manga so something that could tag existing files would be great but might be outside the scope of what this application does.

I'm a programmer myself and I've considered adding this myself but I've no experience in go so I figured I'd ask and see if this is something that would be hard to add

**Comment by darylhjd** [comment]
Do you perhaps have more information on the `ComicInfo.xml` file, such as the fields etc...?

I can't really find alot of information about it.

**Comment by darylhjd** [comment]
I will not be working on this, but if you want to implement it, feel free to open a pull request.

**Comment by AbandonedCart** [comment]
https://github.com/anansi-project/comicinfo for posterity.
