### ISSUE TITLE
[BUG] Manga titles on certain manga not displayed & issue with storing decimal chapters

### ISSUE THREAD

**Issue by dimox99** [darylhjd/mangadesk#52]
1. Bug
Certain Manga titles fail to display when you search for them.
The title column is left blank. As a result, downloading chapters will work, but Mangadesk won't create a subfolder for the manga. Instead Chapters are stored in the downloads folder. This potentially creates a mess, when you download more than one of such title at a time.

2. Bug
Chapter download, folder naming issue
Since some time Mangadex allows uploaders to use decimal chapter numbers, e.g. Chapter 8.5. You can see them as such in Mangadesk. When you download such a chapter, this important dot gets removed, so in the folder the chapter is now named like "Chapter85". Now imagine what happens when you have a manga title with tons of decimal chapter... this creates a mess unless you rename the folders manually - which would lead to the download marker being removed.

**To Reproduce**
Bug 1:
search for "9999" - currently bugs out on on first entry, The manga title is missing. You can acces the manga.
search for "Tenkosuka" - one result, manga title is blank. 

I'm not sure, what causes this. I suspect the titles might being to long or contain nasty characters

Bug 2:
download any manga with decimal chapters, e.g. search for "Kumo desu ga, nani ka"

**Comment by dimox99** [comment]
Hm, always adding those IDs might cause different issues, I guess. The new manga IDs are quite long now, so that's wasting a lot of characters, considering that the combined length of filename+folderpath have their limits. Maybe only use instead of an otherwise blank title?

**Comment by darylhjd** [comment]
yea its not pretty. altho i could just not think so hard and just work with whatever data im given.

anw i dont really have the time to get to bottom of this rn, so ill think abt it when i have the free time.

in the meantime tho i should be able to release a fix just for the 2nd issue.

**Comment by dimox99** [comment]
Albeit it's a bit inconvenient for such titles, Mangadesk still works with them. Just take your time to find a proper solution.

**Comment by dimox99** [comment]
Hi,

is the issue regarding wrong language (Bug 1) also the reason why certain titles cannot be found in Mangadesk - at least for me they cannot be searched for:

Examples:
https://mangadex.org/title/1e8d04cf-400c-4ffb-af6b-108d851f1b7d
https://mangadex.org/title/21b848be-1bfe-4f97-b92c-62d319d8a093

I mean, especially the second title should be easy to find if you look for "giant" but no matter what I try, the search simply returns "no results".

One thing that's special with those two is that they seem to have no description either. At least if I look at them on Mangadex there is none.

**Comment by darylhjd** [comment]
it is due to how the api wrapper i am using for the application parses the data (it cant parse it correctly, so it errors out/doesnt show it).

**Comment by dimox99** [comment]
So, that doesn't sound like an easy fix...

One other strange thing I noticed with searches is that a title may or may not be found depending on the exact keyword you search for. Some seem to not work at all. A good example would be this one:

https://mangadex.org/title/26dd4eae-1bf7-4834-986b-40914cbd5816

Search for "license", "manamusume" or even something plain like "daughter" and it will show up. Well, ofc "daughter" produces quite the list, but the title is still there. Now search for "Boukensha" instead and the list returns... "no results". now that's weird considering the number of titles that should contain this keyword.

Only reason I can imagine here is that there might even be too many results for "Boukensha".

**Comment by darylhjd** [comment]
yup. they were changing the API designs rapidly and it was hard to keep up, so now theres quite a few errors haha,

**Comment by dimox99** [comment]
Yeah, haha. Now they changed API again, I guess. On opening Mangadesk, you now you get "Error loading manga list".

But it's not completely broken. Searching for titles still seems to work, if we exclude above mentioned problems.
