### ISSUE TITLE
[BUG] Error loading Manga List 

### ISSUE THREAD

**Issue by R4zorGTX** [darylhjd/mangadesk#54]
**Describe the bug**

After logging in as a guest, I get the error "Error loading Manga List". 

**To Reproduce**

1. Open mangadesk
2. Log in as a guest  

**Expected behavior**

Gives a list of various manga titles.

**Screenshot** 
![mangadexerror](https://user-images.githubusercontent.com/35612342/142513205-5d0c1fc5-ff10-49f1-b143-514e65107578.PNG)

**Environment** 

- OS: Ubuntu
- Version: 20.04
- Mangadesk v0.6.2 

Maybe the changed something in the API again.

**Comment by darylhjd** [comment]
yup API issue. will look into this when im free.

thanks for reporting!
