### ISSUE TITLE
[Feature Request] Search using Manga ID

### ISSUE THREAD

**Issue by BaccanoMob** [darylhjd/mangadesk#58]
Certain manga are difficult to search (unless they have a really lengthy name). For example, searching for "Katsu!" manga, I get a big list as shown below (had to scroll down below to find it)
![image](https://user-images.githubusercontent.com/82655889/145373164-3d2d9a72-976c-41bf-9ec4-4def567d1b50.png)

This was not the case when I do it in the website itself (pretty much its the first manga).
![image](https://user-images.githubusercontent.com/82655889/145373509-3b76869f-5adc-4fec-85ef-c8beb13e80ee.png)

Though I am not sure how difficult would it be to implement a better search algorithm on par with MD, possible solutions are:

1)to check value inputted in search bar is of the form (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - Typical Manga ID form I noticed) then get the manga directly with the ID.
2)or only check against the ID if there are no results (just to skip verifying if its an Manga ID or not part)
3)recognize a weblink (for example https://mangadex.org/title/1d4291f0-8675-427a-9238-dd186375ff0e/katsu or https://mangadex.org/title/1d4291f0-8675-427a-9238-dd186375ff0e) So you get the exact manga immediately.

**Comment by dimox99** [comment]
or have an "exact search" option, maybe.

Directly accessing a manga by its id would be very nice, though... could also be a separate function "ctrl+i"
But in that case I will be greedy and ask you if it's possible to insert said ID by using copy+paste :smiley_cat:

**Comment by darylhjd** [comment]
just tried developer options on mangadex website.

managed to find the required query parameter to make the results more relevant.

![image](https://user-images.githubusercontent.com/53652695/145391548-60be4c50-548c-4add-9d6d-44d0fc7ce244.png)

**Comment by darylhjd** [comment]
regarding seaching by ID, I won't be supporting that as the API does not support doing so.

**Comment by dimox99** [comment]
> actually you should be able to copy paste in the terminal. however, in some cases you need to use ctrl + alt + c/v instead of just ctrl + c/v

Just downloaded latest version and tried both, with or without alt - neither works for me.

btw. good job on search update! Really like it :smile_cat:

**Comment by darylhjd** [comment]
if you are using windows terminal, you might need to enable it in the terminal settings (not too sure since i dont use windows rn, but thats what i remember)

**Comment by dimox99** [comment]
I run the exe straight from my desktop, so now that you mentioned, I remember. It's possible to use the Edit Menu point and use the Insert option... or you can enable QuickEdit in the window settings. That still won't let me use copy/paste but pushing right mouse button inserts text from windows clipboard then.

Not that I really need it - would only be interesting when searching for IDs and as you already mentioned, that's currently not supported by the API.

**Comment by BaccanoMob** [comment]
> I run the exe straight from my desktop, so now that you mentioned, I remember. It's possible to use the Edit Menu point and use the Insert option... or you can enable QuickEdit in the window settings. That still won't let me use copy/paste but pushing right mouse button inserts text from windows clipboard then.

Im assuming this is what you're looking for: Properties and tick the checkbox to get copy/paste
![image](https://user-images.githubusercontent.com/82655889/145668437-afa1474c-a80a-4cfb-ae6f-c4e9fed81470.png)
<img width="313" alt="image" src="https://user-images.githubusercontent.com/82655889/145668474-f7ba11ea-d341-4bd1-8fc8-f6b6fed8d05d.png">
