### ISSUE TITLE
[Feature Request] Toggle Read Status and Follow Manga option

### ISSUE THREAD

**Issue by BaccanoMob** [darylhjd/mangadesk#59]
As far as I checked (docs and ctrl+K), there is no way to toggle Read status. If there is then please update the docs and ctrl+K help center in the terminal.

I think it would be beneficial to implement this so it be easier to track read changes via the terminal itself (like using ctrl+R to toggle maybe after selecting using ctrl+E/A). 

Mostly suggesting this because volume extras or any kind of bonuses are included in between. Since I periodically delete the downloaded chapters, some nearly got skipped because there is no new update feed in the terminal. So it got me thinking if I can ctrl+A and then ctrl+R, I can track what I download/read even if I delete chapters later.

**Comment by darylhjd** [comment]
mmm seems doable

**Comment by darylhjd** [comment]
i want to design the solution to this properly, so it may take some time!

**Comment by darylhjd** [comment]
theres an issue with the API for now, so im waiting for that to be resolved.

in other words:
D E L A Y E D

**Comment by BaccanoMob** [comment]
Would appreciate if you could include these in Features in Readme.md once they start working (so it be easier to know when the endpoint is fixed).

**Comment by darylhjd** [comment]
tbh i dont want to keep checking either lol, so i wont be doing that.

either way you will know it works when it starts working haha.

**Comment by maxxxed69** [comment]
any way to follow without being logged in?

**Comment by darylhjd** [comment]
> any way to follow without being logged in?

no.
