### ISSUE TITLE
[Feature] Display images on terminal instead of downloading its

### ISSUE THREAD

**Issue by khanhtc1202** [darylhjd/mangadesk#6]
Hi @darylhjd, thanks for your works.

In some cases, instead of persistently stored images locally which could lead to some copyright problems, I guess temporarily store images and let users read directly in their terminal could be a better option.

I think we could use some libraries like [pxl](https://github.com/ichinaski/pxl) or [pixterm](https://github.com/eliukblau/pixterm) for image rendering on terminals. The other things left are: to add new showing screens and navigation on that viewing screen. What do you think about it?

**Comment by darylhjd** [comment]
You are welcome :)

I have those 2 libraries in my sights. Will be experimenting to test out feasibility.

**Comment by jakeisnt** [comment]
My primary concern here would be that the pixelated images provided by those libraries would introduce some reading difficulty.
I think the easiest solution here would be to use another program like `w3mimgdisplay` that's able to show these images at their native resolution and scale them for the terminal.

This is common practice with terminal file browsers like `ranger` and `lf` - [here's a demo of ranger showing native resolution image previews](https://www.youtube.com/watch?v=DJhDMxMgzC0).

**Comment by khanhtc1202** [comment]
> I think the easiest solution here would be to use another program like w3mimgdisplay that's able to show these images at their native resolution and scale them for the terminal.

Sure, that's nice. I use both `ranger` and `lf` too, and nothing to complain about `w3mimgdisplay` features. But does it provide API to interact from go source code or we have to install it as standalone binary first as cli's dependency?

**Comment by jakeisnt** [comment]
You're right, it would have to be installed as a standalone binary and executed with some shell command interface from Go. That can be handled by a package manager or the user can provide an image preview script like `lf` or `ranger` allow for!

**Comment by runoono** [comment]
does the api let you list pages for a chapter? maybe we could set up a command to load images like [TTRV's mailcap system](https://github.com/tildeclub/ttrv/blob/master/ttrv/templates/mailcap) with curl and pipes

**Comment by darylhjd** [comment]
this is near bordering the scope of my knowledge and ability haha

**Comment by runoono** [comment]
can you get a page count? you could make a submenu with sequential page numbers and have users request them one by one. 

as for the commands, you could have them be configured within a config file with a place holder for the page urls such as "curl %page" for example, then execute the command with os/exec during runtime

**Comment by darylhjd** [comment]
there is currently no way to show images with the current UI library (tview) i am using, which is a limitation i am unable to work around.

there are programs out there to show images in the terminal but as far as my knowledge goes i cannot find a way for them to interact with tview, or transfer control back and forth after execution/termination. this includes cross-platform compatibility.

as such i probably will not be pursuing this personally, but i may revisit this in the future.

if anyone can actually accomplish this now, you may create a pull request and we shall have a good discussion :)

**Comment by Kabouik** [comment]
> My primary concern here would be that the pixelated images provided by those libraries would introduce some reading difficulty.
> I think the easiest solution here would be to use another program like `w3mimgdisplay` that's able to show these images at their native resolution and scale them for the terminal.
> 
> This is common practice with terminal file browsers like `ranger` and `lf` - [here's a demo of ranger showing native resolution image previews](https://www.youtube.com/watch?v=DJhDMxMgzC0).

In addition to `w3mimgdisplay`, there are also alternatives like `ueberzug`, kitty terminal's `icat`, and probably a couple users.

I might not be a good example of the potential user base of `mangadesk` since I haven't read mangas in years, but I sure would use it regularly and discover new mangas if I could do everything from the terminal, including viewing images and not having to worry about zooming/scrolling with a mouse or a touch screen.

Very nice project by the way! I came here just to request this feature (as I did on Reddit) and saw this issue already open. :tada:

**Comment by darylhjd** [comment]
Thank you!

I understand this is a highly requested feature but I really really don't know how to do it. I'm sorry :"(

I will try my best!

**Comment by runoono** [comment]
@Kabouik you could try bulk opening it all by running feh *

I'm using this on my fujitsu U810 and i've got a pretty great setup with feh.

Personally I've been trying to get the hang of Go. If I can get the hang of it, I'd love to submit a pr for this

**Comment by Kabouik** [comment]
No problem, thanks for the amazing work already!

**Comment by darylhjd** [comment]
sorry lads, will be closing this :<
