### ISSUE TITLE
[BUG]cant change language

### ISSUE THREAD

**Issue by miodaibuki** [darylhjd/mangadesk#64]
**Describe the bug**
no matter how I change the ISO code in usr_config.json
still can only show en manga

**Comment by darylhjd** [comment]
if possible, would you mind pasting the contents of the usr_config.json file here?

**Comment by darylhjd** [comment]
I have tried adding extra langauges (for example russian)

![image](https://user-images.githubusercontent.com/53652695/147530792-54910a73-2fba-4036-9ef8-628f6187e6ac.png)

and i am able to view russian-translated manga.

![image](https://user-images.githubusercontent.com/53652695/147530824-831914df-2580-410b-8650-a0af1620cb0c.png)

**Comment by darylhjd** [comment]
if you are migrating from an old version of this app, make sure you edit the correct config file. It will be in "AppData/Roaming/mangadesk" folder.

**Comment by miodaibuki** [comment]
> if you are migrating from an old version of this app, make sure you edit the correct config file. It will be in "%AppData%/mangadesk" folder (on Windows).

oh thats the one, thanks for your reply so much, sorry for not making the issue clear
