### ISSUE TITLE
[BUG] Error getting manga list

### ISSUE THREAD

**Issue by maxxxed69** [darylhjd/mangadesk#66]
**Describe the bug**
If in doubt, you may copy the log of the latest run (logs are stored in the `log` folder in mangadesk's configuration folder).
[2022-01-02 20-10-50.log](https://github.com/darylhjd/mangadesk/files/7800246/2022-01-02.20-10-50.log)

**To Reproduce**

1. Launch manga desk
2. Click onguest
3. Error getting manga list.
4. check logs for details

**Expected behavior**
To be able to see and search manga
**Screenshots**

**Environment (please complete the following information):**

- OS: Arch Linux
- Version: 5.15.12-arch1-1

**Additional context**
Add any other context about the problem here, such as whether you have changed any default settings etc.

**Comment by darylhjd** [comment]
what mangadesk version is this

**Comment by darylhjd** [comment]
i did try running the latest version (v0.7.5) and do not get this issue, so most likely you are using an old version which had a problem with the loading.

**Comment by darylhjd** [comment]
have not received any updates, as such ill be closing this issue for now.

if you are still experiencing this problem, please re-open this issue.
