### ISSUE TITLE
[BUG] Issue with Chapter Download

### ISSUE THREAD

**Issue by dimox99** [darylhjd/mangadesk#67]
Currently there seems to be a minor problem when downloading chapters. From my experience, you cannot download a second time from the same manga title without closing and reopening the chapter list first.

Check for yourself... just open a random manga with several chapters and download one of them, doesn't matter which. You can also select multiple chapters. This download will work just fine. Now, once the queue is finished, select another chapter and try to download that one. Everything looks normal and Mangadesk seems to work, it will also tell you that the second download is okay after some time, but when you look in the manga folder there won't be a new subfolder for the second download. This behavior persists until you close the chapter list in Mangadesk and reopen it,

**Comment by darylhjd** [comment]
hmmm okay i tried doing what you said but it seems to download fine for me?

Steps I did:
1. Open a chapter page.
2. Select some chapters to download.
3. Download finishes, add more selections.
4. Try downloading again.
5. Check files, sees new chapters.

Perhaps there's a step that I'm doing wrong to replicate this issue?

**Comment by dimox99** [comment]
current version (0.7.5) Win 8.1 x64, guest mode

Steps are like you listed them.

1. Search for Manga, pick title from list
2. open title/chapter list
3. go to a chapter (lets call it chapter A), press enter and confirm to download.
4. wait for finish message, don't leave chapter list. Chapter is marked as downloaded
5. select another chapter (chapter B), press enter again and start download - still looks like it's working
6. wait for the finish message, then check results:
-> DDL status marker on chapter B is not "Y"
-> in manga folder chapter A subfolder (and content) is present but chapter B subfolder is missing

I don't know what causes this. If it doesn't happen for you it be an OS issue. Thing is, I'm still using the same system and I do know it did not happen in some prior versions. Anyhow, I'm not sure when this happened first. It's not a new one. Might have popped up in 0.6.0 or 0.6.2

**Comment by darylhjd** [comment]
found the issue, thank you!

**Comment by dimox99** [comment]
Ah, I understand. Setting a mark (CTRL+E) on the chapter first circumvents this...
I normally won't be marking a single chapter :smile_cat:
