### ISSUE TITLE
[BUG] Manga list not showing up when searching

### ISSUE THREAD

**Issue by BaccanoMob** [darylhjd/mangadesk#68]
Search not working as intended.
![image](https://user-images.githubusercontent.com/82655889/150098480-942b9ecd-58ca-4453-82b0-0fd63921abc7.png)

Found this comment in the logs when it fails.
> json: cannot unmarshal object into Go struct field Manga.data.relationships of type []mangodex.LocalisedStrings

**Comment by darylhjd** [comment]
Which version of the app are you using? Also, did you search for a particular title? Would help me greatly in identifying the issue.

Thanks!

**Comment by darylhjd** [comment]
> json: cannot unmarshal object into Go struct field Manga.data.relationships of type []mangodex.LocalisedStrings

this makes me think you might be using an old version of the app.

in any case, awaiting more info. thanks!

**Comment by BaccanoMob** [comment]
Yes, apparently I was using an old version. I had to backtrack the downloaded date and check with the date of latest release. Since I usually have the manga followed, I didnt notice till now.

Is it possible to include version number in app? For example like in putting version number on top of Keyboard Mapping section.
![image](https://user-images.githubusercontent.com/82655889/150111200-b2877fa2-6c17-43c3-abfa-ec2ae0030bb7.png)

or next to "Login to Mangadex" or "Welcome to Mangadex, <USERNAME>!"(if logged in) sign
![image](https://user-images.githubusercontent.com/82655889/150111332-8034bfcf-e735-464b-b022-c7a67db31420.png)
Stating "Mangadesk v.0.7.5" or just "v.0.7.5"

I dont think the version number is included anywhere inside the app as well as in properties tab. I know this is minor stuff, but it would much easier to track the version I am using in case I have an issue.

**Comment by darylhjd** [comment]
now that you mentioned it, im embarassed at myself for not realising xd

i will add the version number!
