### ISSUE TITLE
[Feature Request] Add MPR to README

### ISSUE THREAD

**Issue by hiddeninthesand** [darylhjd/mangadesk#71]
I maintain the [`mangadesk`,](https://mpr.makedeb.org/packages/mangadesk) [`mangadesk-git`,](https://mpr.makedeb.org/packages/mangadesk-git) and [`mangadesk-bin`](https://mpr.makedeb.org/packages/mangadesk-bin) packages on the MPR. I believe having it listed in the README would help those trying to install it on Ubuntu.

**Comment by darylhjd** [comment]
thanks for notifying.

im not the best when it comes to package managers, so i am not too sure what the exact instructions will be exactly.

in the near future i think i will create a separate markdown file (which will be linked in the main readme) for installation instructions through package managers. the main readme is getting pretty crowded.

in the meantime, you could submit a small pr adding the install/uninstall instructions for Ubuntu.

thanks!

**Comment by hiddeninthesand** [comment]
Sounds good to me, I'll get right on it.
