### ISSUE TITLE
[BUG] Mangadesk fails to load images

### ISSUE THREAD

**Issue by dimox99** [darylhjd/mangadesk#73]
There seems to be a new issue at the moment.

Until yesterday everything was fine, but when I try downloading mangas now I get a lot of "failed" messages. When looking into it, I noticed that it's somehow related to the image size. At least according to my observation. Images below 1 MB in size are downloaded without trouble. Images around 1.5 MB may cause issues but you might succeed on retry. But if there's any image beyond 2.2 MB it fails downloading for sure. Mangadesk will download images up to that troublesome image, then stop. It will fail on redo until the retry limit is reached.

I tried checking by redownloading a chapter with larger images that I already downloaded some days ago. There was no issue then, now it fails and the images won't load. I also tried on a system with a different ISP, same result.

When accessing chapters through the website, it works, the images will load and they can be saved manually to hard disk one by one, so it's not that the chapters are broken.

Currently using the latest Mangadesk version (0.7.7)

I guess you can check things with any manga title, but if you want one that fails for me, then try this:
https://mangadex.org/title/265da069-ca97-434a-ba54-d118ed9b6e7f
For me, it fail to download chapter 87 completely - first image is over 3MB in size. On the website it's working just fine.

**Comment by darylhjd** [comment]
thanks for the report! will take a look when i have the time

**Comment by darylhjd** [comment]
i have tried downloading this particular manga chapter and it seems to work okay all the time for me.

maybe you could provide a screenshot of the error (and perhaps also the log generated by the program)?

**Comment by dimox99** [comment]
For me the issue persists, I'm not logging in, Mdesk always runs in guest mode.

I looked into the log, seems the error is this:
wsarecv: An existing connection was forcibly closed by the remote host.

This is what angadesk shows - sometimes images might still be downloaded, but most of the time I'm just getting nothing. 
![grafik](https://user-images.githubusercontent.com/90607824/169139202-71879a29-875d-46d8-a8ab-f79cfeaade3b.png)

**Comment by darylhjd** [comment]
paste the entire log here so i can get the fuller picture.

are you also perhaps using any form of firewall/vpn etc. that may affect certain connections?

for now, you may try setting `forcePort443` to true and see if that helps.

**Comment by darylhjd** [comment]
very strange🤔

maybe you can try a vpn on? there is a slight chance they might have blacklisted your original IP for some reason.

**Comment by dimox99** [comment]
I don't really think they blacklisted my IP since I don't have a static IP address. Then, as I also mentioned, using datasaver mode seems to work, at least for now. I guess if it's a blacklisting, then it wouldn't really matter whether I'm using data or data-saver option. Not to mention I can access their website and read stuff online. The issue seems to be related to the images size, especially if they are larger than 1 MB.

**Comment by darylhjd** [comment]
yes in the meantime just stick with data-saver for now.

unfortunately there's not much i can check moving forward as i cannot encounter the problem reliably on my side.

will let this issue stay open for a few weeks. if it resolves by itself, feel free to close the issue :)

**Comment by dimox99** [comment]
Yes, I will do that. It could very well be a temporary ISP issue.

Ah, while I'm at it, short unrelated question: given how the API works, would it be possible to "open/browse" a chapter with Mangadesk before downloading its content? So that you can see a list of images and then for example mark some of them to download only those?

**Comment by darylhjd** [comment]
yes it will provide a list of pages (ie. the file names)

**Comment by dimox99** [comment]
Well, the problem persists and appears might be caused by my ISP :disappointed:

Apart from that, what I can see is that when an error is happening and I tell Mangadesk to retry, the programm won't start loading from the failed image. Instead it will download all images from the top again. Is this intended or an issue of how the API works?

**Comment by darylhjd** [comment]
thanks for the update! i hope the workaround of using data-saver is still working for you.

regarding the retry, yes this is intended, as the download mechanism works by chapter (but not by page).

i am not sure if retrying by page is possible, but i will explore this option when i have the time. i have the impression that it is.

**Comment by darylhjd** [comment]
yea it might be possible, but since this program is more of a downloader than a reader i never thought about downloading just single pages.

**Comment by darylhjd** [comment]
sorry for the late reply btw, been busy.

since it seems no one else is facing the same problem, and there exists a workaround (as unfortunate as it may be), i will proceed to close the issue.

**Comment by dimox99** [comment]
I figures something out... it's highly likely that this behavior is related to my ISP and applies to guest logins. This crap only happens when I use Mangadesk in guest mode with my regular provider, I get disconnected if the image size is a bit larger. 2MB seems fine, 3MB sometimes also... anything beyond that might or might not work at all. Sometimes it does, and then again it's basically not working at all and I can't get a single image downloaded because of d/c.

same machine, different provider, guest mode, data quality: no issues
different machine, same provider, guest mode, data quality: disconnects, depending on current bandwith/line speed

On the other hand, data-saver mode works every single time. But the image quality is significantly lower (not only always jpg but images also get notably downscaled) which sucks. I don't like to use that.

Now here's the thing. I never really logged in with Mangadesk, because it was not necessary to just fetch one or two titles. But after trying, I experienced no further disconnects, even with huge images 10MB+...

My best guess is that they added some protection on the server side to prevent anonymous leeching.

So, case closed, indeed.

**Comment by darylhjd** [comment]
thats some detailed investigation you did!

if someone else faces the same issue in the future it will be useful to know that this is a possible cause.

 thanks for sharing the results of what u found out :D
