### ISSUE TITLE
scoop-shiming - [broken] win

### ISSUE THREAD

**Issue by omaru-ok** [darylhjd/mangadesk#76]
**installtion fails , due to wrong shim **
**`scoop install magnadesk**

**Screenshots**
![image](https://user-images.githubusercontent.com/108952834/196189958-693ac564-eb2f-4e0e-9103-eac413c314f3.png)

- OS: [ Windows-11 X64]
- Mangadesk version: [0.7.8]

**Comment by darylhjd** [comment]
scoop isn't listed as an official way to install mangadesk. i would suggest just to download the exe file from the releases page.
