### ISSUE TITLE
[Feature Request] Config to continue as guest

### ISSUE THREAD

**Issue by Enoumy** [darylhjd/mangadesk#77]
Hi! This is a small feature request for a feature I'm happy to implement. I read the contributing section, and realized that I should submit an issue first to have a discussion on the idea first!

**Is your feature request related to a problem? Please describe.**

Not really a problem, but I tend to always use the login as guest option each time I open up mangadesk as I don't have a mangadex account.

**Describe the solution you'd like**

I'd like to have a flag like `--guest` that skips the login screen.

**Describe alternatives you've considered**

I hackily edited my local mangadesk copy to skip the login screen directly and to also not do a 750ms wait with the following diff:

```diff
mangadesk$ git diff
diff --git a/app/core/credentials.go b/app/core/credentials.go
index ca9524f..5323968 100644
--- a/app/core/credentials.go
+++ b/app/core/credentials.go
@@ -44,8 +44,6 @@ func (m *MangaDesk) loadCredentials() error {
 func (m *MangaDesk) restoreSession() error {
        // Try to read stored credential file.
        if err := m.loadCredentials(); err != nil { // If error, then user was not originally logged in.
-               fmt.Println("No past session, redirecting to login...")
-               time.Sleep(time.Millisecond * 750)
                return err
        }
 
diff --git a/app/ui/login_page.go b/app/ui/login_page.go
index 866896d..328936a 100644
--- a/app/ui/login_page.go
+++ b/app/ui/login_page.go
@@ -20,6 +20,8 @@ func ShowLoginPage() {
 
        core.App.TView.SetFocus(loginPage.Grid)
        core.App.PageHolder.AddAndSwitchToPage(utils.LoginPageID, loginPage.Grid, true)
+       core.App.PageHolder.RemovePage(utils.LoginPageID)
+       ShowMainPage()
 }
 
 // newLoginPage : Creates a new login page.
```
but ideally, I think this should be configurable via a flag.

**Additional context**

If this seems reasonable, I'm happy to put up a pr that adds `--guest`. Thanks! Also unsure if this seems reasonable. Maybe another solution is to remember/persist that the guest login option has been picked?

**Comment by Enoumy** [comment]
Oh whoops, just realized that there is already a nice story for configuration, so I think that instead of a CLI flag, maybe a field in the config.json like `guestLogin` might be better instead?

**Comment by darylhjd** [comment]
hi, yes this would be a good addition to the available configs. i will take a look at the PR when i have a bit more time!
