### ISSUE TITLE
Not all chapter are being displayed

### ISSUE THREAD

**Issue by KlaroMango** [darylhjd/mangadesk#8]
![Screenshot_20210514_111558](https://user-images.githubusercontent.com/84178544/118249567-d7ea6b80-b4a5-11eb-903c-a31248c2206c.png)

The manga is Solo Leveling

**Comment by darylhjd** [comment]
I've checked with the API in Postman:

![image](https://user-images.githubusercontent.com/53652695/118253625-b9ec2d80-b4dc-11eb-8352-737cc25740c3.png)

API returns Chapter 5, then Chapter 65 immediately. 

Based on this, there should be no issue with the displaying of chapters - rather, the chapters do not exist in MangaDex's servers. 

![image](https://user-images.githubusercontent.com/53652695/118254007-2ebf6780-b4dd-11eb-8cf8-1862e589fd33.png)

**Comment by KlaroMango** [comment]
![image](https://user-images.githubusercontent.com/84178544/118262107-b47aed00-b4b4-11eb-87aa-0b2e82a8082f.png)

They do exist tho :(
https://mangadex.tv/manga/pn918005

**Comment by darylhjd** [comment]
thats not the official mangadex site, so i cant help with that.
