### ISSUE TITLE
[BUG] 'NO CHAPTERS!' for all Content

### ISSUE THREAD

**Issue by jaminW55** [darylhjd/mangadesk#82]
**Describe the bug**
If in doubt, you may copy the log of the latest run (logs are stored in the `log` folder in mangadesk's configuration folder).

**To Reproduce**

1. Go to Any Manga
2. Click on It
3. No Chapters!

**Expected behavior**
Chapters to be listed

**Screenshots**
![image](https://github.com/darylhjd/mangadesk/assets/133602605/b2d05695-d0a3-476f-b258-04ad54bfc06d)

**Environment (please complete the following information):**

- OS: Void Linux Musl
- Mangadesk version: 0.7.8_1

**Additional context**
It will also not allow me to login to my own user, so I am just logging in as guest. I just downloaded today and the only modification that I've made has been to set the language to 'ja'

**Comment by darylhjd** [comment]
Hi, thanks for the report.

I just tried logging in and it works for me. Perhaps you mistyped the password?

Also for My Dress-up Darling, it seems there are no japanese chapters available, so no chapters will be shown if you change the language to japanese.
