### ISSUE TITLE
[BUG] Unable to login (Windows)

### ISSUE THREAD

**Issue by Kezess** [darylhjd/mangadesk#84]
**Describe the bug**
I keep getting 'Authentication failed. Try again!' whenever I try to login. I just created the account so the password and username is correct. Here is the log:

2024/05/16 13:50:03 logging.go:49: Session started at 2024-05-16 13-50-03
2024/05/16 13:50:04 service.go:28: Initialised starting screen.
2024/05/16 13:50:04 service.go:32: Running app...
2024/05/16 13:50:18 login_page.go:75: Error trying to login: non-200 status code -> (401) unauthorized_http_exception: User / Password does not match

**To Reproduce**

1. Run app
2. Enter username and password
3. Click Login

**Expected behavior**
Login successfully.

**Environment (please complete the following information):**

- OS: Windows
- Mangadesk version: v0.7.8

**Comment by darylhjd** [comment]
Thanks for the report!

I just tried logging in using my account and it works fine. As the log seems to suggest, the servers have been provided with the wrong username and password combination.

Perhaps you might have copied down the password wrongly after creating your account. If you still have trouble logging in, I would suggest to try changing your password and trying again.

Hope this helps.

**Comment by Kezess** [comment]
Hi, thanks for the fast reply.

I just tried changing my password and I still cannot log in. I have also tried creating a new account and tried to log in on another computer (Windows as well) but I still get the same error.

**Comment by darylhjd** [comment]
Quite strange.

Only thing I can think of that might affect the authentication on our end would be if your password contains special characters that can't be typed normally in a terminal window (i don't know any off the top of my head).

Are you copy and pasting your password or typing it out manually? Does the problem still occur if you use a password with simple characters (e.g. ASCII only)?

**Comment by Kezess** [comment]
I type it out manually. My first password has space in there, then I changed to just numbers and letters (No space and no special characters) but it still gives me the error.

**Comment by darylhjd** [comment]
If you are comfortable with it, you can share with me a previous version of the password that did not work. I will test it on my end to see what the issue is.

**Comment by Kezess** [comment]
Currently my password is VGKFt3857

**Comment by darylhjd** [comment]
it seems that mangadex is deprecating the login APIs. im not exactly sure why it seems to work for my account but perhaps they dont serve new accounts.

unfortunately i think for now you might not be able to use it while logged in.

**Comment by Kezess** [comment]
I see. Thank you for taking your time to help.
