### ISSUE TITLE
Can't backspace in login page

### ISSUE THREAD

**Issue by JonathanTTSouza** [darylhjd/mangadesk#9]
If I type my login wrong I can't backspace and fix it because the help page will show up. I can go back with left arrow key and delete, but can't backspace. Not sure if intended?

**Comment by darylhjd** [comment]
might be an issue with how some terminals interpret different keyboard inputs. 

it happens to me on windows terminal as well but not on bash.

**Comment by PDXChristian** [comment]
The tcell [documentation](https://pkg.go.dev/github.com/gdamore/tcell) states the following:

```
These are the control keys. Note that they overlap with other keys, perhaps. For example, KeyCtrlH is the same as KeyBackspace.
```

The best course of action at this point might be to change the hotkeys.

**Comment by darylhjd** [comment]
nice find. unfortunate that ctrl+H clashes of all keys, but i will have to be changing the key bindings i guess.

**Comment by darylhjd** [comment]
This should also fix any text input fields.

**Comment by JonathanTTSouza** [comment]
> might be an issue with how some terminals interpret different keyboard inputs.
> 
> it happens to me on windows terminal as well but not on bash.
> 
> could you confirm your machine os?

sorry I forgot, it's windows terminal

**Comment by darylhjd** [comment]
no worries :) you may try out the latest release to see if your problem is fixed.

**Comment by JonathanTTSouza** [comment]
Yep, it's working!
